#Velocity config

proxy-name: ""

redis:
  host: ""
  port: 6379

rabbit:
  host: ""
  username: ""
  password: ""

auth-servers:
  - "auth"

#Do not save as last server, and used as auth servers.
forced-servers:
  - "modded"

allowed-commands:
  - "login"
  - "l"
  - "reg"
  - "register"
  - "reg"
  - "email"
  - "captcha"

debug: false
# Do not touch this
config-version: "${velocity.config.version}"